apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-pv
spec:
  capacity:
    storage: 5Gi  # Match the size of your EBS volume
  accessModes:
    - ReadWriteOnce  # EBS volumes are typically `ReadWriteOnce`
  persistentVolumeReclaimPolicy: Retain  # Prevent deletion of the EBS volume when the PV is deleted
  awsElasticBlockStore:
    volumeID: "vol-09102d4112516a114"
    fsType: ext4  # Filesystem type of your EBS volume
