apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify NLB
spec:
  type: LoadBalancer
  selector:
    app: nodered
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
